# Django
# Version: 1.0
FROM ubuntu
# Install Python and Package Libraries
RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
RUN apt-get install -y \
    net-tools \
	python3.6 \
	python3-pip \
	iputils-ping \
	tcpdump \
    vim

# Project Files and Settings

RUN mkdir /root/requirements
RUN mkdir /root/mapped_project_dir
COPY requirements.txt /root/requirements/requirements.txt
WORKDIR /root/requirements
RUN pip3 install -r requirements.txt
WORKDIR /root/mapped_project_dir

# Server
STOPSIGNAL SIGINT
CMD tail -f /dev/null

